/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as FishRouteImport } from './routes/fish'
import { Route as IntelligenceProcessRouteImport } from './routes/intelligence-process'
import { Route as MapRouteImport } from './routes/map'
import { Route as PreDepartureRouteImport } from './routes/pre-departure'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as VoiceRouteImport } from './routes/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FishRoute = FishRouteImport.update({
  id: '/fish',
  path: '/fish',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceProcessRoute = IntelligenceProcessRouteImport.update({
  id: '/intelligence-process',
  path: '/intelligence-process',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PreDepartureRoute = PreDepartureRouteImport.update({
  id: '/pre-departure',
  path: '/pre-departure',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/fish': typeof FishRoute
  '/intelligence-process': typeof IntelligenceProcessRoute
  '/map': typeof MapRoute
  '/pre-departure': typeof PreDepartureRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/fish': typeof FishRoute
  '/intelligence-process': typeof IntelligenceProcessRoute
  '/map': typeof MapRoute
  '/pre-departure': typeof PreDepartureRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/fish': typeof FishRoute
  '/intelligence-process': typeof IntelligenceProcessRoute
  '/map': typeof MapRoute
  '/pre-departure': typeof PreDepartureRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/alerts'
    | '/fish'
    | '/intelligence-process'
    | '/map'
    | '/pre-departure'
    | '/profile'
    | '/safety'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/alerts'
    | '/fish'
    | '/intelligence-process'
    | '/map'
    | '/pre-departure'
    | '/profile'
    | '/safety'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/alerts'
    | '/fish'
    | '/intelligence-process'
    | '/map'
    | '/pre-departure'
    | '/profile'
    | '/safety'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AlertsRoute: typeof AlertsRoute
  FishRoute: typeof FishRoute
  IntelligenceProcessRoute: typeof IntelligenceProcessRoute
  MapRoute: typeof MapRoute
  PreDepartureRoute: typeof PreDepartureRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish': {
      id: '/fish'
      path: '/fish'
      fullPath: '/fish'
      preLoaderRoute: typeof FishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence-process': {
      id: '/intelligence-process'
      path: '/intelligence-process'
      fullPath: '/intelligence-process'
      preLoaderRoute: typeof IntelligenceProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-departure': {
      id: '/pre-departure'
      path: '/pre-departure'
      fullPath: '/pre-departure'
      preLoaderRoute: typeof PreDepartureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AlertsRoute: AlertsRoute,
  FishRoute: FishRoute,
  IntelligenceProcessRoute: IntelligenceProcessRoute,
  MapRoute: MapRoute,
  PreDepartureRoute: PreDepartureRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
